######################################################################
# Automatically generated by qmake (2.01a) mer feb 27 23:47:49 2008
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += ..
LIBS += -L..

DESTDIR = ..

unix:LIBS += -lAttalCommon
unix:LIBS += -lAttalFight
unix:LIBS += -lAttalClient
unix:LIBS += -lAttalAi
unix:LIBS += -lAttalServer

QT += xml network

unix:!macx {
	QMAKE_LFLAGS += -Wl,-rpath,.
}

TARGET = attal-test

# Input
HEADERS += testattal.moc
HEADERS += fakeLoader.h
SOURCES+= fakeLoader.cpp
SOURCES += testattal.cpp 
